language:       ruby
os:             osx
osx_image:      xcode11.5
env:
  global:
    - FRAMEWORK_NAME=Euler
install:
  - swift package resolve # Resolving package
  - swift package update # Updates
  
jobs:
  include:
    - stage: Build
      name: "Jazzy"
      script:
      # Install Jazzy and dependencies
      - gem install jazzy
      - jazzy --clean --no-objc
      - cp Euler.svg ./docs/Euler.svg
      - cp Euclid.png ./docs/Euclid.png
      - cd docs && echo "euler.arguiot.com" > CNAME # Keeps the URL
      deploy:
      - provider:     pages
        skip_cleanup: true
        github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
        keep-history: true
        local-dir:    docs
        on:
          branch:     master
    - script: swift test --parallel
      name: "Tests"
    - stage: Deploy
      name: "CocoaPods"
      script: pod trunk push Euler.podspec --allow-warnings
      # if: tag IS present
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

