language:       ruby
os:             osx
osx_image:      xcode10.2
install:
  # Install Jazzy and dependencies
  - gem install jazzy
script:
  - jazzy --clean --no-objc
  - cd docs && echo "euler.arguiot.com" > CNAME # Keeps the URL
#  - xcodebuild -project SearchKit-Swift.xcodeproj -scheme SearchKit-Swift test
deploy:
  provider:     pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir:    docs
  on:
    branch:     master
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
