language:       ruby
os:             osx
osx_image:      xcode11.5
env:
  global:
    - FRAMEWORK_NAME=Euler
install:
  # Install Jazzy and dependencies
  - gem install jazzy
  - swift package resolve # Resolving package
  - swift package update # Updates
  
jobs:
  include:
    - stage: "Build"
      name: "Jazzy"
      script:
      - jazzy --clean --no-objc
      - cp Euler.svg ./docs/Euler.svg
      - cp Euclid.png ./docs/Euclid.png
      - cd docs && echo "euler.arguiot.com" > CNAME # Keeps the URL
    - script: swift test --parallel
      name: "Tests"
    - stage: deploy
      name: "CocoaPods"
      script: pod trunk push Euler.podspec --allow-warnings


deploy:
  - provider:     pages
    cleanup:      false
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir:    docs
    on:
      branch:     master
#   - provider: releases
#     api_key: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
#     file: $FRAMEWORK_NAME.framework.zip
#     skip_cleanup: true
#     on:
#       tags: true
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

