language:       ruby
os:             osx
osx_image:      xcode10.2
install:
  # Install Jazzy and dependencies
  - gem install jazzy
script:
  - "jazzy --clean --no-objc --author 'Arthur Guiot' --author_url https://arguiot.com --github_url https://github.com/arguiot/Euler --github-file-prefix https://github.com/arguiot/Euler/blob/master/ --output docs --theme fullwidth --swift-build-tool spm --build-tool-arguments -Xswiftc,-swift-version,-Xswiftc,5"
#  - xcodebuild -project SearchKit-Swift.xcodeproj -scheme SearchKit-Swift test
deploy:
  provider:     pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir:    docs
  on:
    branch:     master
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
