name: Jazzy

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Copy ressources
      run: mkdir docs & cp Euler.svg ./docs/Euler.svg & cp Euclid.png ./docs/Euclid.png & cd docs & echo "euler.arguiot.com" > CNAME
    - name: Publish Jazzy Docs
      # You may pin to the exact commit or the version.
      # uses: Steven0351/publish-jazzy-docs@9ac83856c845f4b7d4803f1ebb3bbc2fa85bbfdd
      uses: Steven0351/publish-jazzy-docs@v1.1.2
      with:
        # Path to .jazzy.yml file - preferred
        config: .jazzy.yml
        # Arguments to pass to Jazzy
        args: "--clean --no-objc"
        # Personal access token
        personal_access_token: ${{ secrets.GITHUB_TOKEN }}
