name: Swift

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install Swift
      run: sudo apt-get install clang libicu-dev git && mkdir ~/.swiftenv && git clone https://github.com/kylef/swiftenv ~/.swiftenv && echo 'export SWIFTENV_ROOT="$HOME/.swiftenv"' >> ~/.bashrc && echo 'export PATH="$SWIFTENV_ROOT/bin:$PATH"' >> ~/.bashrc && echo 'eval "$(swiftenv init -)"' >> ~/.bashrc && source ~/.bashrc && swiftenv install 5.1.2
      if: runner.os == ubuntu-latest
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
