name: Swift

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install Swift Dependencies
      run: sudo apt-get install clang libicu-dev
      if: runner.os == 'Linux'
    - name: Download Swift
      run: wget "https://swift.org/builds/swift-5.1.3-release/ubuntu1804/swift-5.1.3-RELEASE/swift-5.1.3-RELEASE-ubuntu18.04.tar.gz"
      if: runner.os == 'Linux'
    - name: Install Swift
      run: |
        tar xzf swift-5.1.3-RELEASE-ubuntu18.04.tar.gz
        echo "::add-path::$(pwd)/swift-5.1.3-RELEASE-ubuntu18.04/usr/bin"
      if: runner.os == 'Linux'
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
